### ISSUE TITLE
Double spawned projectiles in netplay

### ISSUE THREAD

**Issue by Vagabond** [omf2097/openomf#139]
With enough lag, the client can have 2 projectiles spawned at once. If they both hit, the har damage can get out of sync temporarily. This is mainly cosmetic but should be fixed sometime.

**Comment by katajakasa** [comment]
Currently it seems that Player 2 always spawns two projectiles, the second one right after the first one has completed. Both projectiles do damage. Player 1 only shows 1 projectile appearing and hitting.

**Comment by Vagabond** [comment]
No longer an issue with the new netplay.
