### ISSUE TITLE
Minor graphics glitch with xBRZ

### ISSUE THREAD

**Issue by animehunter** [omf2097/openomf#181]
Player ones HAR (the jaguar on the left) shows a green outline.
https://www.dropbox.com/s/wtmjbkgnsrfd5dg/openomf%20outline%20bug.png

Can be reproduced using:
Arena: Power plant
Scaler: 4xBRZ
Resolution: 1280x800

**Comment by katajakasa** [comment]
This should be fixed now, btw. There was an xBRZ bug.
