### ISSUE TITLE
Enemy positioning during throws

### ISSUE THREAD

**Issue by Vagabond** [omf2097/openomf#256]
There's some inaccuracies with how the enemy is positioned during throws (both jaguar throws, Gargoyle's throw, etc). This used to work better before I 'fixed' Jaguar's scrap/destruct. I *think* there's some tags that we don't handle right now that affect this. ox and oy, maybe?

**Comment by katajakasa** [comment]
Should be fixed in 9f19e24c5ee60e1c5bf29da556723eebf353c907.

Closing for now; reopen if necessary.
