### ISSUE TITLE
Main menu sound and music bars need to go all the way to "off"

### ISSUE THREAD

**Issue by katajakasa** [omf2097/openomf#268]
The sound and music volume bars need to be able to go all the way to "off" position. Currently they only go down to one level.

**Comment by exander77** [comment]
My pull request fixes that, it allows go to zero, but it means that n position slider has n + 1 states (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10), but I think it corresponds with the original game.

**Comment by katajakasa** [comment]
Yup, this is indeed done.
