### ISSUE TITLE
No libenet7 in ubuntu 14.04.2, can you rewrite for libenet2a?

### ISSUE THREAD

**Issue by zaggynl** [omf2097/openomf#284]
Workaround:
cd /usr/lib/x86_64-linux-gnu
sudo ln -s libenet.so.2 libenet.so.7

**Comment by katajakasa** [comment]
Notes from IRC discussion: It seems like we can just switch to libenet2a; will have to check the libenet packaging situation in at least ubuntu and debian. libenet2a and libenet7 packages should contain the same version of libenet, but the library files are named differently.

**Comment by katajakasa** [comment]
Okay, debian Jessie only has libenet7 available, while Sid has both :/

**Comment by rasb23** [comment]
Confirmed the 
https://github.com/omf2097/openomf/commit/3566366f66166a23522ea4ff41a48217fcdaaba8

**Comment by katajakasa** [comment]
libenet7 (which we depend on) should now be standard everywhere. Closing this ad deprecated.
