### ISSUE TITLE
HAR color change on fire damage

### ISSUE THREAD

**Issue by gdeda** [omf2097/openomf#297]
HAR won't turn orange-red and return gradually on its normal shade when taking fire damage (Pyros' damage and the fireball in the pit)

**Comment by katajakasa** [comment]
This is related to how we handle HAR based palette transformations (see har_palette_transform() in har.c). We don't quite know how these work yet, so our current implementation is really buggy. This will be fixed as we find out more.

**Comment by Vagabond** [comment]
Resolved
