### ISSUE TITLE
winning HAR should touch floor before going winning anim

### ISSUE THREAD

**Issue by gdeda** [omf2097/openomf#300]
(This is quite a fun thing, aka: Pyros' win animation could happen at mid-air!):

if Pyros' finishing move is the "jet hit and flight" (kick button while on air), the winning animation can happen before Pyros is touching floor, and it starts to hover mid-air.

I have some difficulties to reproduce a similar situation with other HARs but I believe, coding-wise, the issue is generic.

**Comment by Vagabond** [comment]
I have seen this with jaguar as well.

**Comment by Vagabond** [comment]
I can't seem to reproduce this anymore.

**Comment by katajakasa** [comment]
Also cannot reproduce. On both Pyros and Jaguar, the HAR lands and then goes to victory animation. Closing as fixed. Let's create a new ticket if this reappears.
