### ISSUE TITLE
SDL2 2.0.4

### ISSUE THREAD

**Issue by katajakasa** [omf2097/openomf#318]
We need to test SDL2 v2.0.4, and make sure everything works. Also, it might now be possible to remove some of our bugfix hacks.

**Comment by katajakasa** [comment]
Tested OpenOMF on 2.0.4, our current code works.

**Comment by Vagabond** [comment]
Here's some release notes, I think:

https://forums.libsdl.org/viewtopic.php?t=11305

Seems like a win?

**Comment by katajakasa** [comment]
Here's the official changelog:
https://hg.libsdl.org/SDL/file/b2fd76446eee/WhatsNew.txt

Looks like they didn't fix the software renderer bugs yet :(

**Comment by Vagabond** [comment]
Have they been filed?

**Comment by katajakasa** [comment]
Yes, in the renderer part of SDL bugtracker. They don't seem like a very high priority, though.

**Comment by katajakasa** [comment]
Looks like no problems with 2.0.5 either. Renderer still not fixed, though :/

**Comment by katajakasa** [comment]
I'm closing this, since the original comment has already been handled. We can open a new one when 2.0.6 comes up :)
