### ISSUE TITLE
Flail: Opponent HAR moves toward attacking HAR during "throw" attack

### ISSUE THREAD

**Issue by Rondom** [omf2097/openomf#323]
Not really sure how the attack is called, it is the same combo that is used for throwing with other HARs such as Jaguar i.e. is going FORWARD right next to the opponent HAR and then PUNCH.

Sometimes the opponent HAR moves toward the Flail during the attack and moves further behind Flail's back while still being hurt by each hit carried out by the attack. Whether this behaviour occurs, seems to depend on the behaviour of the opponent HAR because I could not reproduce it while playing in two-player-mode with the second player doing nothing.
Also I am wondering whether the fact that the opponent Pyros disappears in one of the screenshots is a bug or a feature (as in one frame of an animation that one usually does not notice).

Logfile: 
[flail_opponent_moves_away_log.txt](https://github.com/omf2097/openomf/files/101978/flail_opponent_moves_away_log.txt)
Screenshots:
- [screenshot_15090](https://cloud.githubusercontent.com/assets/125913/12531893/5b6005a8-c206-11e5-9f30-f7929a1ff97c.png)
- [screenshot_15455](https://cloud.githubusercontent.com/assets/125913/12531891/5b5e3926-c206-11e5-8824-ebeab0bdb8e8.png)
- [screenshot_15737](https://cloud.githubusercontent.com/assets/125913/12531892/5b5ed390-c206-11e5-87d4-90284974bbfb.png)
- [screenshot_16003](https://cloud.githubusercontent.com/assets/125913/12531887/5b469d52-c206-11e5-9e15-c3f231def0d7.png)
- [screenshot_16235](https://cloud.githubusercontent.com/assets/125913/12531890/5b49c3a6-c206-11e5-84ce-4cea2fe45221.png)
- [screenshot_16440](https://cloud.githubusercontent.com/assets/125913/12531885/5b43d996-c206-11e5-9c45-0d9b7c9f76f9.png)
- [screenshot_16631](https://cloud.githubusercontent.com/assets/125913/12531888/5b48c276-c206-11e5-96d7-c38904aa2e6e.png)
- [screenshot_16816](https://cloud.githubusercontent.com/assets/125913/12531886/5b43f6ba-c206-11e5-8504-e441136334ef.png)
- [screenshot_17003](https://cloud.githubusercontent.com/assets/125913/12531889/5b496316-c206-11e5-9031-2f7b8618fe45.png)

![screenshot_16440](https://cloud.githubusercontent.com/assets/125913/12531885/5b43d996-c206-11e5-9c45-0d9b7c9f76f9.png)

**Comment by katajakasa** [comment]
Should be fixed as of 9bf53cf0f5d5c97bbc30168e1a62a14c765abbdb

**Comment by Rondom** [comment]
Thanks :-) 👍
