### ISSUE TITLE
INSTALL: compile need libargtable2-dev 

### ISSUE THREAD

**Issue by rasb23** [omf2097/openomf#326]
Compiled on ubuntu-mate 16.04 following the INSTALL guide and I got the following:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ARGTABLE2_INCLUDE_DIR (ADVANCED)

It was easy to fix with installing libargtable2-dev. Should this be added to the list of required libraries? Is this an issue on other platforms?

**Comment by katajakasa** [comment]
This is because argtable2 dependency was added just recentry, but we forgot to update docs.

Fixed in 2fb2fd1fe9011865f4c2a6349794ef9b91fe08e5
