### ISSUE TITLE
SDL 2.0.6 audio issues on windows

### ISSUE THREAD

**Issue by katajakasa** [omf2097/openomf#346]
On windows, audio playback suggers from clicks and popping. Can be fixed by using directsound backend. See https://discourse.libsdl.org/t/sdl-hint-audio-resampling-mode/23196 for more details.

Should we check SDL version string and set directsound if 2.0.6 found ? Looks like 2.0.7 is going to be pushed out fast with bugfixes :/

**Comment by Vagabond** [comment]
When, on windows, would you NOT want to use directsound?

**Comment by katajakasa** [comment]
Directsound is deprecated. The api of choice nowadays is WASAPI (which the SDL2 tries to use).

**Comment by katajakasa** [comment]
SDL 2.0.7 fixed everything. Since 2.0.6 did not have much time to live and looks like 2.0.7 has pretty much replaced it everywhere, I think we can just close this. No 2.0.6 specific hacks required.
