### ISSUE TITLE
Key presses stops registering.

### ISSUE THREAD

**Issue by Ryrynz** [omf2097/openomf#365]
At random times it seems after taking a hit from the opponent key presses no longer function until I take another hit, once that happens the keys begin to function again.

**Comment by katajakasa** [comment]
Interesting. I cannot repeat this, everything seems to work correctly. What system/OS/keyboard are you using ?

**Comment by Ryrynz** [comment]
Windows 10 1909 64-bit. Razer Huntsman Elite. 0.65.

**Comment by katajakasa** [comment]
Latest builds are always available here: https://buildbot.openomf.org/artifacts/ -- could you test that one ?

**Comment by Ryrynz** [comment]
Thanks, I played a few rounds and had no issues. Performance was a little all over the place on my quad core i5, sometimes fast, sometimes a bit slow, CPU was only at about 15-20% utilization. Also any way to double or even maximize the graphics to use the whole screen at this point?

**Comment by katajakasa** [comment]
Graphics should be fully configurable in the in-game video settings menu (fullscreen too).

Are you sure the slowdowns are not just the game feature where game slows down after certain successful hits ? This is slightly more visible in openomf than the original game currently.

**Comment by Ryrynz** [comment]
Don't know, I certainly didn't configure it for that and it was quite bad when it happened, however the new version fixed it.

**Comment by katajakasa** [comment]
Closing as fixed :)
