### ISSUE TITLE
One Must Fall 2100

### ISSUE THREAD

**Issue by XargonWan** [omf2097/openomf#368]
My idea is to keep the actual OpenOMF identical to the original (when that status is reached) and move all the enhancement to a new (but same) project called One Must Fall 2100, the sequel that One Must Fall 2097 deserves that was in the mind of Rob Elam but he scrappet to make Battlegrounds.

We can recap and continue with the story arc started in OMF but three years later (instead of 20) to keep the game more nearby the original one, keep all the old robots maybe with a minor change if needed but basically untouched.

We can give a name to the 4 unamed pilots that we can choose in OMF tournament and canoize them giving them a backstory, create new villian/s and so on.
Of course we can take some ideas from the Battlegrounds, like the robots, some pilots, some arenas but completely changing their stile matching with OMF 2097 and creating our onw original content.

Even if the game will be dranw in 3D will remain a 2D scorlling fighting game.
The main theme would be a remake/remixed version of the original one so It can be recognizable.

What do you think about it?

PS: someone had never contacted Rob Elam itself to ask him to join the project?

**Comment by katajakasa** [comment]
This is certainly possible, but likely not on the current openomf engine. Currently, loading the original sprites and resources and handling the movement, levels etc. are so hardcoded that making what you suggest would likely be easier on some other (well documented and completed) game engine would be a better idea, and as a completely separate project.

As for Rob Elam, I remember that there was some contact, but that never moved anywhere :)

**Comment by joneirik** [comment]
Just to comment that Rob Elam hasn't shown any interest in doing anything with 2097 since the first time I've seen anyone be in contact with him (1998 when he opened his own website/forum for omfbg).

And he is busy with his own projects last I saw/heard of him, so really doubt it.
