### ISSUE TITLE
good job!

### ISSUE THREAD

**Issue by ghost** [omf2097/openomf#386]
Hey I tested it today on ARM Linux and works "perfectly". there are a lots of physics to fix bc the robots jump like crazy
but it's far better compared to previous versions.

also, I laughed a loooot when the gamepad started to vibrate hahahahah nice touch.

I will make a video later on, but I will wait for better physics

best regards,

**Comment by katajakasa** [comment]
Nice! :) Yeah, the jumping is unfortunately off due to issue #245 . Someone needs to figure out how all the modifiers affect stuff like movement speed and jumping etc. Currently we're working on reversing the old game (sloowly), so progress on the code itself is more or less on halt :(

**Comment by Askmewho** [comment]
Yeah, not an easy task indeed.
