### ISSUE TITLE
AI does not capitalize on stuns

### ISSUE THREAD

**Issue by katajakasa** [omf2097/openomf#433]
AI does not seem to capitalize on enemy HAR stuns. They should probably be taken advantage of more aggressively.

**Comment by Snafulator** [comment]
Hmm. So when a high difficulty AI detects a stun it is very likely to queue the charge tactics, which works well for HARs like the thor or flail.. but for the other HARs I will need to make them walk the distance without getting distracted by new instructions.

I think this is something I can fix.

**Comment by katajakasa** [comment]
Resolved by #456
