### ISSUE TITLE
Flatpak?

### ISSUE THREAD

**Issue by Ronald-Diemicke** [omf2097/openomf#462]
Would love to see a flatpak of this to make getting it running on the steamdeck easier!

**Comment by katajakasa** [comment]
Hey! Currently we're not considering adding any more distribution options, as that would cut into the (already almost nonexistent) time we have for developing the actual code. I would seriously suggest getting dosbox working and then playing OMF there, as currently that is much more feature-complete (and MUCH less buggy). OpenOMF is very much pre-alpha, developer testing only stuff.

**Comment by Rasenberry** [comment]
I can confirm that OMF works great with emudeck on steamdeck. It was the first thing I going running. Even uploaded the icons to steamgriddb.
