### ISSUE TITLE
Feat.req. OMF2097 1.0 preview demo version support

### ISSUE THREAD

**Issue by necros2k7** [omf2097/openomf#493]
@Vagabond
@katajakasa 
subj

**Comment by katajakasa** [comment]
I don't understand the issue

**Comment by necros2k7** [comment]
@katajakasa  I mean support of running demo OMF2097 1.0 release version

**Comment by katajakasa** [comment]
Ah. That is unlikely to happen. The demo is quite different in its formats and workings, so it is not in scope of this project. Maybe someday, if someone has the time and interest, but with our current pace that is likely to be about hundred years in the future.
