### ISSUE TITLE
Windows ARM release

### ISSUE THREAD

**Issue by katajakasa** [omf2097/openomf#539]
As per request https://github.com/omf2097/openomf/discussions/527

TODO (probably ?):
- [ ] Figure out what compiler and configuration we need for this (mingw + arm possible ?)
- [ ] If MSVC is required, then implement msvc support
- [ ] Build or find windows arm libraries and put them somewhere for the CI to find (https://github.com/omf2097/openomf-win-build)
- [ ] Build the CI scripts for autoreleases

**Comment by talynone** [comment]
Looks like someone ported it to ARM here:

https://github.com/mijk84/win-arm64-binaries/releases/tag/openomf

**Comment by Nopey** [comment]
Closed by https://github.com/omf2097/openomf/pull/781
(although the resulting binaries are as of yet untested)
