### ISSUE TITLE
How to extract original assets to be used for resources?

### ISSUE THREAD

**Issue by futurepr0n** [omf2097/openomf#548]
Hi all. I have been trying to build for Mac but look to be failing to compile properly, I think this because the format of my OMF2097 is basically the installer disk. Is there a way to extract the contents or do you need to install a vm, install it on it natively then rip the assets over to your pc of choice?

just curious since no explicit mention of that, but it’s the only way I can see it being possible given my limited knowledge of working with the installers .

**Comment by mrannanj** [comment]
What is the compile error you are getting? The assets in http://www.omf2097.com/pub/files/omf/omf2097.rar need to be extracted with unrar or such.

**Comment by mrannanj** [comment]
Can you join our Discord so I can fix the mac packages for you? https://discord.gg/7CPPzab

**Comment by futurepr0n** [comment]
Thanks, will try this. Not at my PC so without the exact error, but it was fairly obvious that the resources were not in their expected format. Appreciate the link, I’ll try using this and close the issue if success. Since the instructions say to use the assets but without explicitly linking to this rar, I think my assets were not available to be used. It couldn’t find the proper stuff. On Aug 28, 2024, at 10:31 AM, Martti Rannanjärvi ***@***.***> wrote:﻿
What is the compile error you are getting? The assets in http://www.omf2097.com/pub/files/omf/omf2097.rar need to be extracted with unrar or such.

**Comment by futurepr0n** [comment]
Thanks, joined the discord, and now seem to be further, but still having an issue:
<img width="760" alt="Screenshot 2024-08-28 at 8 58 21 PM" src="https://github.com/user-attachments/assets/ff0208c4-6c93-4149-815e-a5ff8bd12774">

    "CONFUSE_INCLUDE_DIR-NOTFOUND"
